export type SpiceLevel = 'mild' | 'medium' | 'hot' | 'none';

export interface ModifierOption {
  id: string;
  label: string;
  extraPrice: number; // pence
}

export interface ModifierGroup {
  id: string;
  label: string;
  required: boolean;
  multiSelect: boolean;
  options: ModifierOption[];
}

export interface MenuItem {
  id: string;
  categoryId: string;
  name: string;
  description: string;
  price: number; // pence
  image: string;
  alt: string;
  isVegetarian: boolean;
  spiceLevel: SpiceLevel;
  allergens: string[];
  available: boolean;
  featured: boolean;
  eposItemId: string;
  modifierGroups: ModifierGroup[];
}

export interface MenuCategory {
  id: string;
  name: string;
  emoji: string;
  displayOrder: number;
}

export const MENU_CATEGORIES: MenuCategory[] = [
{ id: 'all', name: 'All', emoji: '🍽️', displayOrder: 0 },
{ id: 'starters', name: 'Starters', emoji: '🌶️', displayOrder: 1 },
{ id: 'any-timers', name: 'Any Timers', emoji: '🍛', displayOrder: 2 },
{ id: 'thalis', name: 'Thalis & Rice', emoji: '🥘', displayOrder: 3 },
{ id: 'soups', name: 'Soups', emoji: '🍲', displayOrder: 4 },
{ id: 'dosas', name: 'Dosas', emoji: '🫓', displayOrder: 5 },
{ id: 'special-dosas', name: 'Special Dosas', emoji: '⭐', displayOrder: 6 },
{ id: 'uthappam', name: 'Uthappam', emoji: '🥞', displayOrder: 7 },
{ id: 'breads-curries', name: 'Breads & Curries', emoji: '🫶', displayOrder: 8 },
{ id: 'rice-noodles', name: 'Rice & Noodles', emoji: '🍚', displayOrder: 9 },
{ id: 'chaat', name: 'Chaat & Specials', emoji: '🎉', displayOrder: 10 },
{ id: 'desserts', name: 'Desserts', emoji: '🍮', displayOrder: 11 },
{ id: 'drinks', name: 'Drinks', emoji: '🥤', displayOrder: 12 }];


export const MENU_ITEMS: MenuItem[] = [
// ─── STARTERS ───────────────────────────────────────────────────────────────
{
  id: 'item-gobi-65',
  categoryId: 'starters',
  name: 'Gobi 65',
  description: 'Spicy, crunchy batter-fried cauliflower preparation.',
  price: 899,
  image: 'https://dosacompany.co.uk/wp-content/uploads/2026/01/Gobi65.jpeg',
  alt: 'Crispy golden Gobi 65 cauliflower bites garnished with curry leaves',
  isVegetarian: true,
  spiceLevel: 'hot',
  allergens: ['gluten'],
  available: true,
  featured: true,
  eposItemId: 'EPS-001',
  modifierGroups: []
},
{
  id: 'item-paneer-65',
  categoryId: 'starters',
  name: 'Paneer 65',
  description: 'Spicy, crunchy batter-fried cubed cottage cheese preparation.',
  price: 949,
  image: 'https://dosacompany.co.uk/wp-content/uploads/2026/01/Paneer65.jpeg',
  alt: 'Golden fried paneer 65 cubes with spicy coating and green chillies',
  isVegetarian: true,
  spiceLevel: 'medium',
  allergens: ['dairy', 'gluten'],
  available: true,
  featured: false,
  eposItemId: 'EPS-002',
  modifierGroups: []
},
{
  id: 'item-chilly-paneer',
  categoryId: 'starters',
  name: 'Chilly Paneer',
  description: 'Fried cottage cheese tossed with onions, green chillies, red chilly paste & scallions.',
  price: 999,
  image: 'https://dosacompany.co.uk/wp-content/uploads/2026/01/Chillipaneer.jpeg',
  alt: 'Chilly paneer with colourful peppers and spring onions in a wok',
  isVegetarian: true,
  spiceLevel: 'hot',
  allergens: ['dairy', 'soy'],
  available: true,
  featured: false,
  eposItemId: 'EPS-003',
  modifierGroups: [
  {
    id: 'mg-chilly-style',
    label: 'Style',
    required: true,
    multiSelect: false,
    options: [
    { id: 'opt-dry', label: 'Dry', extraPrice: 0 },
    { id: 'opt-gravy', label: 'Gravy', extraPrice: 0 }]

  }]

},
{
  id: 'item-chilly-mushroom',
  categoryId: 'starters',
  name: 'Chilly Mushroom',
  description: 'Fried mushroom tossed with onions, green chillies, red chilly paste & scallions.',
  price: 949,
  image: 'https://dosacompany.co.uk/wp-content/uploads/2026/01/Mushroom65.jpeg',
  alt: 'Stir-fried chilly mushroom with peppers and spring onions',
  isVegetarian: true,
  spiceLevel: 'hot',
  allergens: ['soy'],
  available: true,
  featured: false,
  eposItemId: 'EPS-004',
  modifierGroups: [
  {
    id: 'mg-mushroom-style',
    label: 'Style',
    required: true,
    multiSelect: false,
    options: [
    { id: 'opt-dry', label: 'Dry', extraPrice: 0 },
    { id: 'opt-gravy', label: 'Gravy', extraPrice: 0 }]

  }]

},
{
  id: 'item-chilly-baby-corn',
  categoryId: 'starters',
  name: 'Chilly Baby Corn',
  description: 'Baby corn tossed with onions, green chillies, red chilly paste & scallions.',
  price: 999,
  image: 'https://dosacompany.co.uk/wp-content/uploads/2026/01/Babycorn65-1.jpeg',
  alt: 'Crispy chilly baby corn starter with colourful peppers',
  isVegetarian: true,
  spiceLevel: 'hot',
  allergens: ['gluten'],
  available: true,
  featured: false,
  eposItemId: 'EPS-005',
  modifierGroups: []
},
{
  id: 'item-mushroom-pepper-fry',
  categoryId: 'starters',
  name: 'Mushroom Pepper Fry',
  description: 'Button mushroom tossed with Chettinad spices and pounded pepper corns.',
  price: 949,
  image: 'https://dosacompany.co.uk/wp-content/uploads/2026/01/MushroomPepperFr.jpeg',
  alt: 'Mushroom pepper fry with whole peppercorns and curry leaves',
  isVegetarian: true,
  spiceLevel: 'hot',
  allergens: [],
  available: true,
  featured: false,
  eposItemId: 'EPS-006',
  modifierGroups: []
},
{
  id: 'item-veg-manchurian',
  categoryId: 'starters',
  name: 'Vegetable Manchurian',
  description: 'Batter-fried mixed vegetable balls tossed with oriental style sauce.',
  price: 949,
  image: 'https://dosacompany.co.uk/wp-content/uploads/2026/01/VegetableManchurianDryGrav.jpeg',
  alt: 'Vegetable Manchurian balls in dark sauce with spring onions',
  isVegetarian: true,
  spiceLevel: 'medium',
  allergens: ['gluten', 'soy'],
  available: true,
  featured: false,
  eposItemId: 'EPS-007',
  modifierGroups: [
  {
    id: 'mg-manchurian-style',
    label: 'Style',
    required: true,
    multiSelect: false,
    options: [
    { id: 'opt-dry', label: 'Dry', extraPrice: 0 },
    { id: 'opt-gravy', label: 'Gravy', extraPrice: 0 }]

  }]

},
{
  id: 'item-gobi-manchurian',
  categoryId: 'starters',
  name: 'Gobi Manchurian',
  description: 'Batter-fried cauliflower florets tossed with oriental style sauce.',
  price: 949,
  image: 'https://dosacompany.co.uk/wp-content/uploads/2026/01/GobiManchurian.jpeg',
  alt: 'Gobi Manchurian cauliflower in glossy sauce garnished with spring onions',
  isVegetarian: true,
  spiceLevel: 'medium',
  allergens: ['gluten', 'soy'],
  available: true,
  featured: false,
  eposItemId: 'EPS-008',
  modifierGroups: [
  {
    id: 'mg-gobi-manchurian-style',
    label: 'Style',
    required: true,
    multiSelect: false,
    options: [
    { id: 'opt-dry', label: 'Dry', extraPrice: 0 },
    { id: 'opt-gravy', label: 'Gravy', extraPrice: 0 }]

  }]

},
{
  id: 'item-bhindi-kurkure',
  categoryId: 'starters',
  name: 'Bhindi Kurkure',
  description: 'Thin sliced okra fried with spiced batter coating.',
  price: 899,
  image: 'https://dosacompany.co.uk/wp-content/uploads/2026/01/BhindiKurkura.jpeg',
  alt: 'Crispy bhindi kurkure okra fries with spiced coating',
  isVegetarian: true,
  spiceLevel: 'medium',
  allergens: ['gluten'],
  available: true,
  featured: false,
  eposItemId: 'EPS-009',
  modifierGroups: []
},
{
  id: 'item-chilli-mogo',
  categoryId: 'starters',
  name: 'Chilli Mogo',
  description: 'Fried cassava tossed with onions, green chillies, red chilly paste & scallions.',
  price: 999,
  image: 'https://dosacompany.co.uk/wp-content/uploads/2026/01/Spicymasalamogo.jpeg',
  alt: 'Chilli mogo cassava fries with spicy sauce and herbs',
  isVegetarian: true,
  spiceLevel: 'hot',
  allergens: [],
  available: true,
  featured: false,
  eposItemId: 'EPS-010',
  modifierGroups: []
},
{
  id: 'item-fried-dosa-chips',
  categoryId: 'starters',
  name: 'Fried Dosa Chips',
  description: 'Our signature starter of thin fried rice crepe chips.',
  price: 875,
  image: 'https://dosacompany.co.uk/wp-content/uploads/2026/01/FriedDosaChip.jpeg',
  alt: 'Crispy fried dosa chips served with chutneys',
  isVegetarian: true,
  spiceLevel: 'mild',
  allergens: [],
  available: true,
  featured: false,
  eposItemId: 'EPS-011',
  modifierGroups: []
},
{
  id: 'item-masala-pappad',
  categoryId: 'starters',
  name: 'Masala Pappad',
  description: 'Fried pappad with mixture of chopped onion.',
  price: 875,
  image: 'https://dosacompany.co.uk/wp-content/uploads/2026/01/MasalaPappa.jpeg',
  alt: 'Masala pappad topped with chopped onions and spices',
  isVegetarian: true,
  spiceLevel: 'mild',
  allergens: ['gluten'],
  available: true,
  featured: false,
  eposItemId: 'EPS-012',
  modifierGroups: []
},
{
  id: 'item-tandoori-paneer-tikka',
  categoryId: 'starters',
  name: 'Tandoori Paneer Tikka',
  description: 'Cheesy hung curd marinated cottage cheese cooked in clay oven.',
  price: 875,
  image: 'https://dosacompany.co.uk/wp-content/uploads/2026/01/Paneer65.jpeg',
  alt: 'Tandoori paneer tikka skewers with charred marks and mint chutney',
  isVegetarian: true,
  spiceLevel: 'medium',
  allergens: ['dairy'],
  available: true,
  featured: false,
  eposItemId: 'EPS-013',
  modifierGroups: []
},

// ─── ANY TIMERS ──────────────────────────────────────────────────────────────
{
  id: 'item-idly',
  categoryId: 'any-timers',
  name: 'Idly',
  description: 'All-time favourite steamed rice cakes served with sambar and chutney.',
  price: 550,
  image: 'https://dosacompany.co.uk/wp-content/uploads/2026/01/WhatsApp-Image-2026-01-19-at-01.32.18.jpeg',
  alt: 'Soft steamed idly rice cakes served with sambar and coconut chutney',
  isVegetarian: true,
  spiceLevel: 'none',
  allergens: [],
  available: true,
  featured: true,
  eposItemId: 'EPS-020',
  modifierGroups: [
  {
    id: 'mg-idly-extras',
    label: 'Extras',
    required: false,
    multiSelect: true,
    options: [
    { id: 'opt-extra-sambar', label: 'Extra Sambar', extraPrice: 100 },
    { id: 'opt-extra-chutney', label: 'Extra Chutney', extraPrice: 75 },
    { id: 'opt-ghee', label: 'Add Ghee', extraPrice: 50 }]

  }]

},
{
  id: 'item-mini-idly',
  categoryId: 'any-timers',
  name: 'Mini Idly (14 Nos)',
  description: 'Steamed mini rice cakes served with sambar separate, garnished with ghee and chopped cilantro.',
  price: 649,
  image: 'https://dosacompany.co.uk/wp-content/uploads/2026/01/mini-idly.jpeg',
  alt: 'Fourteen mini idly rice cakes in a bowl with sambar and ghee',
  isVegetarian: true,
  spiceLevel: 'none',
  allergens: ['dairy'],
  available: true,
  featured: false,
  eposItemId: 'EPS-021',
  modifierGroups: []
},
{
  id: 'item-kaima-idly',
  categoryId: 'any-timers',
  name: 'Kaima Idly',
  description: 'Deep fried idlies tossed with Indian spices & served with raitha.',
  price: 949,
  image: 'https://dosacompany.co.uk/wp-content/uploads/2026/01/KaimaIdl.jpeg',
  alt: 'Kaima idly deep fried idli pieces tossed in spices with raitha',
  isVegetarian: true,
  spiceLevel: 'medium',
  allergens: ['dairy'],
  available: true,
  featured: false,
  eposItemId: 'EPS-022',
  modifierGroups: []
},
{
  id: 'item-ghee-podi-idly',
  categoryId: 'any-timers',
  name: 'Ghee Podi Idly',
  description: 'Idly tossed with idly chilly powder and desi ghee.',
  price: 799,
  image: 'https://dosacompany.co.uk/wp-content/uploads/2026/01/GheePodiIdl.jpeg',
  alt: 'Ghee podi idly coated in spiced powder and golden ghee',
  isVegetarian: true,
  spiceLevel: 'mild',
  allergens: ['dairy'],
  available: true,
  featured: false,
  eposItemId: 'EPS-023',
  modifierGroups: []
},
{
  id: 'item-medhu-vada',
  categoryId: 'any-timers',
  name: 'Medhu Vada (2 Nos)',
  description: 'Doughnut-shaped deep-fried crispy batter of urad dhal.',
  price: 550,
  image: 'https://dosacompany.co.uk/wp-content/uploads/2026/01/MedhuVada.jpeg',
  alt: 'Two crispy medhu vada doughnuts with sambar and chutney',
  isVegetarian: true,
  spiceLevel: 'mild',
  allergens: ['gluten'],
  available: true,
  featured: false,
  eposItemId: 'EPS-024',
  modifierGroups: []
},
{
  id: 'item-sambar-vada',
  categoryId: 'any-timers',
  name: 'Sambar/Rasam Vada (2 Nos)',
  description: 'Dipped in sambar or rasam.',
  price: 699,
  image: 'https://dosacompany.co.uk/wp-content/uploads/2026/01/SambarVad.jpeg',
  alt: 'Vada dipped in sambar broth served in a bowl',
  isVegetarian: true,
  spiceLevel: 'mild',
  allergens: ['gluten'],
  available: true,
  featured: false,
  eposItemId: 'EPS-025',
  modifierGroups: [
  {
    id: 'mg-vada-dip',
    label: 'Choose Dip',
    required: true,
    multiSelect: false,
    options: [
    { id: 'opt-sambar', label: 'Sambar', extraPrice: 0 },
    { id: 'opt-rasam', label: 'Rasam', extraPrice: 0 }]

  }]

},
{
  id: 'item-curd-vada',
  categoryId: 'any-timers',
  name: 'Curd Vada (2 Nos)',
  description: 'Fried vada dipped in creamy tempered yoghurt, garnished with fresh cilantro.',
  price: 699,
  image: 'https://dosacompany.co.uk/wp-content/uploads/2026/01/Curdvada2No.jpeg',
  alt: 'Curd vada in creamy yoghurt with mustard seeds and cilantro garnish',
  isVegetarian: true,
  spiceLevel: 'none',
  allergens: ['dairy', 'gluten'],
  available: true,
  featured: false,
  eposItemId: 'EPS-026',
  modifierGroups: []
},
{
  id: 'item-poori-masala',
  categoryId: 'any-timers',
  name: 'Poori Masala (3 Nos)',
  description: 'Fried fluffy whole wheat bread served with potato masala.',
  price: 650,
  image: 'https://dosacompany.co.uk/wp-content/uploads/2026/01/PooriMasala3No.jpeg',
  alt: 'Three puffed poori breads with spiced potato masala',
  isVegetarian: true,
  spiceLevel: 'mild',
  allergens: ['gluten'],
  available: true,
  featured: false,
  eposItemId: 'EPS-027',
  modifierGroups: []
},
{
  id: 'item-chapathy-kuruma',
  categoryId: 'any-timers',
  name: 'Chapathy Kuruma (2 Nos)',
  description: 'Whole wheat bread served with mix vegetable gravy.',
  price: 699,
  image: 'https://dosacompany.co.uk/wp-content/uploads/2026/01/ChapathiKurma2pcs.jpeg',
  alt: 'Two chapathi flatbreads with mixed vegetable kuruma gravy',
  isVegetarian: true,
  spiceLevel: 'mild',
  allergens: ['gluten'],
  available: true,
  featured: false,
  eposItemId: 'EPS-028',
  modifierGroups: []
},
{
  id: 'item-parotta-kuruma',
  categoryId: 'any-timers',
  name: 'Parotta Kuruma (2 Nos)',
  description: 'Chennai style layered refined flour bread cooked in griddle, served with mix vegetable gravy.',
  price: 799,
  image: 'https://dosacompany.co.uk/wp-content/uploads/2026/01/ParottaKuruma2No.jpeg',
  alt: 'Flaky layered parotta with vegetable kuruma gravy',
  isVegetarian: true,
  spiceLevel: 'mild',
  allergens: ['gluten'],
  available: true,
  featured: false,
  eposItemId: 'EPS-029',
  modifierGroups: []
},
{
  id: 'item-chilly-parotta',
  categoryId: 'any-timers',
  name: 'Chilly Parotta',
  description: 'Deep fried cubes cut parotta tossed with Indian spices and served with raitha.',
  price: 999,
  image: 'https://dosacompany.co.uk/wp-content/uploads/2026/01/ChillyParott.jpeg',
  alt: 'Chilly parotta cubes tossed in spices with raitha on the side',
  isVegetarian: true,
  spiceLevel: 'hot',
  allergens: ['gluten'],
  available: true,
  featured: false,
  eposItemId: 'EPS-030',
  modifierGroups: []
},
{
  id: 'item-ghee-pongal',
  categoryId: 'any-timers',
  name: 'Ghee Pongal',
  description: 'Rice and moong dal tempered in ghee with pepper, cumin seeds & cashew nuts.',
  price: 650,
  image: 'https://dosacompany.co.uk/wp-content/uploads/2026/01/GheePonga.jpeg',
  alt: 'Creamy ghee pongal rice with cashews and black pepper',
  isVegetarian: true,
  spiceLevel: 'mild',
  allergens: ['dairy', 'nuts'],
  available: true,
  featured: false,
  eposItemId: 'EPS-031',
  modifierGroups: []
},
{
  id: 'item-choley-batoora',
  categoryId: 'any-timers',
  name: 'Choley Batoora (2 Nos)',
  description: 'Deep fried Indian bread served with spiced chickpea gravy.',
  price: 899,
  image: 'https://dosacompany.co.uk/wp-content/uploads/2026/01/CholeyBhatura2pcs.jpeg',
  alt: 'Puffed bhatura bread with spiced chana masala chickpea curry',
  isVegetarian: true,
  spiceLevel: 'medium',
  allergens: ['gluten'],
  available: true,
  featured: false,
  eposItemId: 'EPS-032',
  modifierGroups: []
},
{
  id: 'item-poori-sheera',
  categoryId: 'any-timers',
  name: 'Poori Sheera (3 Nos)',
  description: 'Fried fluffy whole wheat bread served with desi style semolina sweet preparation.',
  price: 699,
  image: 'https://dosacompany.co.uk/wp-content/uploads/2026/01/PooriSheera3No.jpeg',
  alt: 'Three poori breads with sweet semolina sheera halwa',
  isVegetarian: true,
  spiceLevel: 'none',
  allergens: ['gluten', 'dairy', 'nuts'],
  available: true,
  featured: false,
  eposItemId: 'EPS-033',
  modifierGroups: []
},

// ─── THALIS & RICE ───────────────────────────────────────────────────────────
{
  id: 'item-bombay-thali',
  categoryId: 'thalis',
  name: 'Bombay Thali (Limited)',
  description: 'Mini lassi, roti, channa, dhal, paneer dish, veg dish, pulao, raitha, salad, sweet, papad & pickle.',
  price: 1299,
  image: 'https://dosacompany.co.uk/wp-content/uploads/2026/01/BombayThali.jpeg',
  alt: 'Bombay thali platter with multiple small bowls of curries, rice and bread',
  isVegetarian: true,
  spiceLevel: 'medium',
  allergens: ['dairy', 'gluten', 'nuts'],
  available: true,
  featured: true,
  eposItemId: 'EPS-040',
  modifierGroups: []
},
{
  id: 'item-madras-thali',
  categoryId: 'thalis',
  name: 'Madras Thali (Limited)',
  description: 'Sweet, chapathy, kurma, steamed rice, sambar, rasam, poriyal, kuzhambu, curd, appalam & pickle.',
  price: 1299,
  image: 'https://dosacompany.co.uk/wp-content/uploads/2026/01/MadrasThali.jpeg',
  alt: 'Traditional Madras thali on banana leaf with rice, sambar and curries',
  isVegetarian: true,
  spiceLevel: 'medium',
  allergens: ['dairy'],
  available: true,
  featured: false,
  eposItemId: 'EPS-041',
  modifierGroups: []
},
{
  id: 'item-quick-lunch',
  categoryId: 'thalis',
  name: 'Quick Lunch (Limited)',
  description: 'Sweet, chapathy kurma, sambar rice, curd rice, pulao, poriyal, appalam & pickle.',
  price: 999,
  image: 'https://dosacompany.co.uk/wp-content/uploads/2026/01/QuickLunchLimite.jpeg',
  alt: 'Quick lunch thali with rice, curries and accompaniments',
  isVegetarian: true,
  spiceLevel: 'mild',
  allergens: ['dairy', 'gluten'],
  available: true,
  featured: false,
  eposItemId: 'EPS-042',
  modifierGroups: []
},
{
  id: 'item-rice-of-the-day',
  categoryId: 'thalis',
  name: 'Rice Of The Day',
  description: 'Ask our waiter for the speciality of the day.',
  price: 825,
  image: 'https://dosacompany.co.uk/wp-content/uploads/2026/01/RiceOfTheDa.jpeg',
  alt: 'Special rice dish of the day served with accompaniments',
  isVegetarian: true,
  spiceLevel: 'mild',
  allergens: [],
  available: true,
  featured: false,
  eposItemId: 'EPS-043',
  modifierGroups: []
},
{
  id: 'item-curd-rice',
  categoryId: 'thalis',
  name: 'Curd Rice',
  description: 'Mashed rice mixed with cream tempered yogurt & milk.',
  price: 699,
  image: 'https://dosacompany.co.uk/wp-content/uploads/2026/01/CurdRice.jpeg',
  alt: 'Creamy curd rice with mustard seeds and curry leaves tempering',
  isVegetarian: true,
  spiceLevel: 'none',
  allergens: ['dairy'],
  available: true,
  featured: false,
  eposItemId: 'EPS-044',
  modifierGroups: []
},
{
  id: 'item-plain-rice',
  categoryId: 'thalis',
  name: 'Plain Rice',
  description: 'Sona Masoori steamed rice.',
  price: 450,
  image: 'https://dosacompany.co.uk/wp-content/uploads/2026/01/PlainRic.jpeg',
  alt: 'Plain steamed sona masoori rice in a bowl',
  isVegetarian: true,
  spiceLevel: 'none',
  allergens: [],
  available: true,
  featured: false,
  eposItemId: 'EPS-045',
  modifierGroups: []
},
{
  id: 'item-steamed-rice',
  categoryId: 'thalis',
  name: 'Steamed Rice',
  description: 'Basmati rice.',
  price: 499,
  image: 'https://dosacompany.co.uk/wp-content/uploads/2026/01/SteamedRic.jpeg',
  alt: 'Fluffy steamed basmati rice in a bowl',
  isVegetarian: true,
  spiceLevel: 'none',
  allergens: [],
  available: true,
  featured: false,
  eposItemId: 'EPS-046',
  modifierGroups: []
},

// ─── SOUPS ───────────────────────────────────────────────────────────────────
{
  id: 'item-hot-sour',
  categoryId: 'soups',
  name: 'Vegetable Hot & Sour',
  description: 'A tangy, spicy Indo-Chinese style vegetable soup.',
  price: 499,
  image: 'https://dosacompany.co.uk/wp-content/uploads/2026/01/VegetableHotSou.jpeg',
  alt: 'Hot and sour vegetable soup with vegetables and vinegar',
  isVegetarian: true,
  spiceLevel: 'hot',
  allergens: ['soy'],
  available: true,
  featured: false,
  eposItemId: 'EPS-050',
  modifierGroups: []
},
{
  id: 'item-sweet-corn-soup',
  categoryId: 'soups',
  name: 'Sweet Corn Vegetable',
  description: 'Creamy sweet corn vegetable soup.',
  price: 499,
  image: 'https://dosacompany.co.uk/wp-content/uploads/2026/01/SweetCornVegetabl.jpeg',
  alt: 'Sweet corn vegetable soup with corn kernels and vegetables',
  isVegetarian: true,
  spiceLevel: 'mild',
  allergens: [],
  available: true,
  featured: false,
  eposItemId: 'EPS-051',
  modifierGroups: []
},
{
  id: 'item-rasam',
  categoryId: 'soups',
  name: 'Chennai Spl Rasam',
  description: 'Traditional South Indian peppery tamarind soup, a digestive classic.',
  price: 499,
  image: 'https://dosacompany.co.uk/wp-content/uploads/2026/01/ChennaiSplRasa.jpeg',
  alt: 'Chennai special rasam peppery tamarind soup in a bowl',
  isVegetarian: true,
  spiceLevel: 'hot',
  allergens: [],
  available: true,
  featured: false,
  eposItemId: 'EPS-052',
  modifierGroups: []
},

// ─── DOSAS ───────────────────────────────────────────────────────────────────
{
  id: 'item-plain-dosa',
  categoryId: 'dosas',
  name: 'Plain Dosa',
  description: 'Classic thin and crispy dosa served with sambar and coconut chutney.',
  price: 699,
  image: 'https://dosacompany.co.uk/wp-content/uploads/2026/01/Plain-Dosa.png',
  alt: 'Thin crispy plain dosa rolled on a plate with sambar and chutney',
  isVegetarian: true,
  spiceLevel: 'none',
  allergens: [],
  available: true,
  featured: false,
  eposItemId: 'EPS-060',
  modifierGroups: []
},
{
  id: 'item-masala-dosa',
  categoryId: 'dosas',
  name: 'Masala Dosa',
  description: 'Potato mixture stuffed dosa served with sambar and coconut chutney.',
  price: 799,
  image: 'https://dosacompany.co.uk/wp-content/uploads/2026/01/MasalaDosa.jpg',
  alt: 'Golden crispy masala dosa filled with spiced potato masala',
  isVegetarian: true,
  spiceLevel: 'mild',
  allergens: [],
  available: true,
  featured: true,
  eposItemId: 'EPS-061',
  modifierGroups: [
  {
    id: 'mg-dosa-chutney',
    label: 'Choose Chutney',
    required: true,
    multiSelect: false,
    options: [
    { id: 'opt-coconut', label: 'Coconut Chutney', extraPrice: 0 },
    { id: 'opt-tomato', label: 'Tomato Chutney', extraPrice: 0 },
    { id: 'opt-both', label: 'Both Chutneys', extraPrice: 0 }]

  },
  {
    id: 'mg-dosa-extras',
    label: 'Extras',
    required: false,
    multiSelect: true,
    options: [
    { id: 'opt-extra-sambar', label: 'Extra Sambar', extraPrice: 100 },
    { id: 'opt-extra-chutney', label: 'Extra Chutney', extraPrice: 75 },
    { id: 'opt-extra-masala', label: 'Extra Masala', extraPrice: 299 }]

  }]

},
{
  id: 'item-ghee-dosa',
  categoryId: 'dosas',
  name: 'Ghee Dosa',
  description: 'Crispy dosa cooked with pure ghee.',
  price: 799,
  image: 'https://dosacompany.co.uk/wp-content/uploads/2026/01/GheeDos.jpeg',
  alt: 'Golden ghee dosa glistening with clarified butter',
  isVegetarian: true,
  spiceLevel: 'none',
  allergens: ['dairy'],
  available: true,
  featured: false,
  eposItemId: 'EPS-062',
  modifierGroups: []
},
{
  id: 'item-ghee-masala-dosa',
  categoryId: 'dosas',
  name: 'Ghee Masala Dosa',
  description: 'Golden dosa enriched with pure ghee and filled with spiced potato masala.',
  price: 875,
  image: 'https://dosacompany.co.uk/wp-content/uploads/2026/01/GheeMasalaDos.jpeg',
  alt: 'Ghee masala dosa with potato filling and golden ghee coating',
  isVegetarian: true,
  spiceLevel: 'mild',
  allergens: ['dairy'],
  available: true,
  featured: false,
  eposItemId: 'EPS-063',
  modifierGroups: []
},
{
  id: 'item-ghee-podi-dosa',
  categoryId: 'dosas',
  name: 'Ghee Podi Dosa',
  description: 'Crispy dosa cooked with ghee and spiced podi powder.',
  price: 1099,
  image: 'https://dosacompany.co.uk/wp-content/uploads/2026/01/GheePodiDosa.jpeg',
  alt: 'Ghee podi dosa with spiced powder and clarified butter',
  isVegetarian: true,
  spiceLevel: 'medium',
  allergens: ['dairy'],
  available: true,
  featured: false,
  eposItemId: 'EPS-064',
  modifierGroups: []
},
{
  id: 'item-ghee-podi-masala-dosa',
  categoryId: 'dosas',
  name: 'Ghee Podi Masala Dosa',
  description: 'Crispy dosa with ghee, podi and potato masala stuffing.',
  price: 1199,
  image: 'https://dosacompany.co.uk/wp-content/uploads/2026/01/GheePodiDos.jpeg',
  alt: 'Ghee podi masala dosa with spiced powder, ghee and potato filling',
  isVegetarian: true,
  spiceLevel: 'medium',
  allergens: ['dairy'],
  available: true,
  featured: false,
  eposItemId: 'EPS-065',
  modifierGroups: []
},
{
  id: 'item-onion-dosa',
  categoryId: 'dosas',
  name: 'Onion Dosa',
  description: 'Chopped onion and podi sprinkled on dosa.',
  price: 775,
  image: 'https://dosacompany.co.uk/wp-content/uploads/2026/01/Onion-Dos.jpeg',
  alt: 'Crispy onion dosa with caramelised onions on top',
  isVegetarian: true,
  spiceLevel: 'mild',
  allergens: [],
  available: true,
  featured: false,
  eposItemId: 'EPS-066',
  modifierGroups: []
},
{
  id: 'item-onion-podi-dosa',
  categoryId: 'dosas',
  name: 'Onion Podi Dosa',
  description: 'Chopped onion and podi sprinkled on dosa.',
  price: 825,
  image: 'https://dosacompany.co.uk/wp-content/uploads/2026/01/OnionPodiDos.jpeg',
  alt: 'Onion podi dosa with spiced powder and onions',
  isVegetarian: true,
  spiceLevel: 'medium',
  allergens: [],
  available: true,
  featured: false,
  eposItemId: 'EPS-067',
  modifierGroups: []
},
{
  id: 'item-onion-podi-masala-dosa',
  categoryId: 'dosas',
  name: 'Onion Podi Masala Dosa',
  description: 'Chopped onion, podi sprinkled on dosa with potato masala mixture.',
  price: 899,
  image: 'https://dosacompany.co.uk/wp-content/uploads/2026/01/masal-onion.jpeg',
  alt: 'Onion podi masala dosa with potato filling and spiced powder',
  isVegetarian: true,
  spiceLevel: 'medium',
  allergens: [],
  available: true,
  featured: false,
  eposItemId: 'EPS-068',
  modifierGroups: []
},
{
  id: 'item-fusion-mysore-masala-dosa',
  categoryId: 'dosas',
  name: 'Fusion Mysore Masala Dosa',
  description: 'Red chutney and podi sprinkled on dosa with potato masala stuffing.',
  price: 1149,
  image: 'https://dosacompany.co.uk/wp-content/uploads/2026/01/FusionMysoreMasalaDos.jpeg',
  alt: 'Fusion Mysore masala dosa with red chutney and potato filling',
  isVegetarian: true,
  spiceLevel: 'hot',
  allergens: [],
  available: true,
  featured: false,
  eposItemId: 'EPS-069',
  modifierGroups: []
},
{
  id: 'item-chocolate-dosa',
  categoryId: 'dosas',
  name: 'Chocolate Dosa',
  description: 'Hazelnut-based Nutella evenly spread on dosa.',
  price: 825,
  image: 'https://dosacompany.co.uk/wp-content/uploads/2026/01/ChocolateDos.jpeg',
  alt: 'Chocolate dosa with Nutella spread on a thin crispy crepe',
  isVegetarian: true,
  spiceLevel: 'none',
  allergens: ['dairy', 'nuts', 'gluten'],
  available: true,
  featured: false,
  eposItemId: 'EPS-070',
  modifierGroups: []
},
{
  id: 'item-cheese-dosa',
  categoryId: 'dosas',
  name: 'Cheese Dosa',
  description: 'Crispy dosa topped with melted cheddar cheese.',
  price: 799,
  image: 'https://dosacompany.co.uk/wp-content/uploads/2026/01/CheeseDos.jpeg',
  alt: 'Cheese dosa with melted cheddar on a crispy dosa',
  isVegetarian: true,
  spiceLevel: 'none',
  allergens: ['dairy'],
  available: true,
  featured: false,
  eposItemId: 'EPS-071',
  modifierGroups: []
},
{
  id: 'item-cheese-podi-dosa',
  categoryId: 'dosas',
  name: 'Cheese Podi Dosa',
  description: 'Grated cheddar cheese, podi sprinkled on dosa.',
  price: 949,
  image: 'https://dosacompany.co.uk/wp-content/uploads/2026/01/CheesePodiDos.jpeg',
  alt: 'Cheese podi dosa with grated cheese and spiced powder',
  isVegetarian: true,
  spiceLevel: 'medium',
  allergens: ['dairy'],
  available: true,
  featured: false,
  eposItemId: 'EPS-072',
  modifierGroups: []
},
{
  id: 'item-cheese-podi-masala-dosa',
  categoryId: 'dosas',
  name: 'Cheese Podi Masala Dosa',
  description: 'Grated cheddar cheese, podi sprinkled on dosa & stuffed with potato masala.',
  price: 999,
  image: 'https://dosacompany.co.uk/wp-content/uploads/2026/01/CheesePodiMasalaDos.jpeg',
  alt: 'Cheese podi masala dosa with cheese, podi and potato filling',
  isVegetarian: true,
  spiceLevel: 'medium',
  allergens: ['dairy'],
  available: true,
  featured: false,
  eposItemId: 'EPS-073',
  modifierGroups: []
},
{
  id: 'item-paneer-masala-dosa',
  categoryId: 'dosas',
  name: 'Paneer Masala Dosa',
  description: 'Grated paneer burji masala dosa.',
  price: 1199,
  image: 'https://dosacompany.co.uk/wp-content/uploads/2026/01/PaneerMasalaDos.jpeg',
  alt: 'Paneer masala dosa with spiced cottage cheese filling',
  isVegetarian: true,
  spiceLevel: 'medium',
  allergens: ['dairy'],
  available: true,
  featured: false,
  eposItemId: 'EPS-074',
  modifierGroups: []
},
{
  id: 'item-butter-masala-dosa',
  categoryId: 'dosas',
  name: 'Butter Masala Dosa',
  description: 'Dosa cooked with pure butter & stuffed with potato masala mix.',
  price: 999,
  image: 'https://dosacompany.co.uk/wp-content/uploads/2026/01/ButterMasalaDos.jpeg',
  alt: 'Butter masala dosa with golden butter and potato masala',
  isVegetarian: true,
  spiceLevel: 'mild',
  allergens: ['dairy'],
  available: true,
  featured: false,
  eposItemId: 'EPS-075',
  modifierGroups: []
},
{
  id: 'item-plain-rava-dosa',
  categoryId: 'dosas',
  name: 'Plain Rava Dosa',
  description: 'A special dosa made out of semolina, refined flour, rice flour & spices.',
  price: 950,
  image: 'https://dosacompany.co.uk/wp-content/uploads/2026/01/PlainRavaDos.jpeg',
  alt: 'Lacy crispy plain rava dosa made from semolina',
  isVegetarian: true,
  spiceLevel: 'mild',
  allergens: ['gluten'],
  available: true,
  featured: false,
  eposItemId: 'EPS-076',
  modifierGroups: []
},
{
  id: 'item-onion-rava-dosa',
  categoryId: 'dosas',
  name: 'Onion Rava Dosa',
  description: 'Chopped onion spread on rava dosa.',
  price: 999,
  image: 'https://dosacompany.co.uk/wp-content/uploads/2026/01/OnionRavaDos.jpeg',
  alt: 'Lacy onion rava dosa with caramelised onions',
  isVegetarian: true,
  spiceLevel: 'mild',
  allergens: ['gluten'],
  available: true,
  featured: false,
  eposItemId: 'EPS-077',
  modifierGroups: []
},
{
  id: 'item-onion-rava-masala-dosa',
  categoryId: 'dosas',
  name: 'Onion Rava Masala Dosa',
  description: 'Chopped onion spread on rava dosa & stuffed with potato masala.',
  price: 1250,
  image: 'https://dosacompany.co.uk/wp-content/uploads/2026/01/OnionRavaMasalaDos.jpeg',
  alt: 'Onion rava masala dosa with potato filling and caramelised onions',
  isVegetarian: true,
  spiceLevel: 'mild',
  allergens: ['gluten'],
  available: true,
  featured: false,
  eposItemId: 'EPS-078',
  modifierGroups: []
},
{
  id: 'item-dryfruit-rava-dosa',
  categoryId: 'dosas',
  name: 'DryFruit Rava Dosa',
  description: 'Royal blend of dry fruits sprinkled & cooked rava dosa.',
  price: 1299,
  image: 'https://dosacompany.co.uk/wp-content/uploads/2026/01/DryFruitRavaDos.jpeg',
  alt: 'Dry fruit rava dosa with cashews, raisins and almonds',
  isVegetarian: true,
  spiceLevel: 'none',
  allergens: ['gluten', 'nuts'],
  available: true,
  featured: false,
  eposItemId: 'EPS-079',
  modifierGroups: []
},

// ─── UTHAPPAM ────────────────────────────────────────────────────────────────
{
  id: 'item-vadivelu-uthappam',
  categoryId: 'uthappam',
  name: 'Vadivelu Uthappam',
  description: 'Madras famous thick rice pancake with chopped onion, carrot, podi and generous ghee.',
  price: 950,
  image: 'https://dosacompany.co.uk/wp-content/uploads/2026/01/VadiveluUthappa.jpeg',
  alt: 'Thick Vadivelu uthappam rice pancake with onions and carrots',
  isVegetarian: true,
  spiceLevel: 'medium',
  allergens: ['dairy'],
  available: true,
  featured: false,
  eposItemId: 'EPS-080',
  modifierGroups: []
},
{
  id: 'item-mixed-uthappam',
  categoryId: 'uthappam',
  name: 'Mixed Uthappam',
  description: 'Onion, tomato, capsicum, black pepper, cilantro & podi with optional cheddar cheese.',
  price: 999,
  image: 'https://dosacompany.co.uk/wp-content/uploads/2026/01/MixedUthappa.jpeg',
  alt: 'Mixed uthappam with colourful vegetable toppings',
  isVegetarian: true,
  spiceLevel: 'medium',
  allergens: ['dairy'],
  available: true,
  featured: false,
  eposItemId: 'EPS-081',
  modifierGroups: [
  {
    id: 'mg-uthappam-cheese',
    label: 'Add Cheese?',
    required: false,
    multiSelect: false,
    options: [
    { id: 'opt-no-cheese', label: 'No Cheese', extraPrice: 0 },
    { id: 'opt-add-cheese', label: 'Add Cheddar Cheese', extraPrice: 0 }]

  }]

},
{
  id: 'item-pizza-uthappam',
  categoryId: 'uthappam',
  name: 'Pizza Uthappam',
  description: 'Onion, tomato, capsicum, black pepper, cilantro & podi with optional cheddar cheese.',
  price: 1099,
  image: 'https://dosacompany.co.uk/wp-content/uploads/2026/01/PizzaUthappam.jpeg',
  alt: 'Pizza uthappam with pizza-style toppings and melted cheese',
  isVegetarian: true,
  spiceLevel: 'medium',
  allergens: ['dairy', 'gluten'],
  available: true,
  featured: false,
  eposItemId: 'EPS-082',
  modifierGroups: []
},

// ─── SPECIAL DOSAS ───────────────────────────────────────────────────────────
{
  id: 'item-karuvepilai-podi-dosa',
  categoryId: 'special-dosas',
  name: 'Karuvepilai Podi Dosa',
  description: 'Sundried curry leaves, spice blend powder sprinkled dosa.',
  price: 950,
  image: 'https://dosacompany.co.uk/wp-content/uploads/2026/01/KaraikudiKaalanKariMasalaDos.jpeg',
  alt: 'Karuvepilai podi dosa with curry leaf spice powder',
  isVegetarian: true,
  spiceLevel: 'medium',
  allergens: [],
  available: true,
  featured: false,
  eposItemId: 'EPS-090',
  modifierGroups: []
},
{
  id: 'item-karaikudi-dosa',
  categoryId: 'special-dosas',
  name: 'Karaikudi Kaalan Kari Masala Dosa',
  description: 'Perfect dosa for mushroom lovers with Chettinad spice blend.',
  price: 1050,
  image: 'https://dosacompany.co.uk/wp-content/uploads/2026/01/KaraikudiKaalanKariMasalaDos.jpeg',
  alt: 'Karaikudi mushroom masala dosa with Chettinad spices',
  isVegetarian: true,
  spiceLevel: 'hot',
  allergens: [],
  available: true,
  featured: false,
  eposItemId: 'EPS-091',
  modifierGroups: []
},
{
  id: 'item-mooligai-dosa',
  categoryId: 'special-dosas',
  name: 'Mooligai Masala Dosa',
  description: 'Organic tulsi leaves paste, cheese, garlic and nuts spread on dosa cooked with extra virgin olive oil.',
  price: 1050,
  image: 'https://dosacompany.co.uk/wp-content/uploads/2026/01/mogili.jpeg',
  alt: 'Mooligai masala dosa with herbal tulsi paste and nuts',
  isVegetarian: true,
  spiceLevel: 'mild',
  allergens: ['dairy', 'nuts'],
  available: true,
  featured: false,
  eposItemId: 'EPS-092',
  modifierGroups: []
},
{
  id: 'item-karuppu-dosa',
  categoryId: 'special-dosas',
  name: 'Karuppu Dosa',
  description: 'Edible activated charcoal infused dosa cooked with ghee.',
  price: 1050,
  image: 'https://dosacompany.co.uk/wp-content/uploads/2026/01/KaruppuDosa.jpeg',
  alt: 'Black Karuppu dosa made with activated charcoal and ghee',
  isVegetarian: true,
  spiceLevel: 'mild',
  allergens: ['dairy'],
  available: true,
  featured: false,
  eposItemId: 'EPS-093',
  modifierGroups: []
},
{
  id: 'item-palak-dosa',
  categoryId: 'special-dosas',
  name: 'Palak Masala Dosa',
  description: 'Tempered spinach purée spread on dosa with potato masala mix.',
  price: 1050,
  image: 'https://dosacompany.co.uk/wp-content/uploads/2026/01/PalakMasalaDos.jpeg',
  alt: 'Green palak masala dosa with spinach puree and potato filling',
  isVegetarian: true,
  spiceLevel: 'mild',
  allergens: [],
  available: true,
  featured: false,
  eposItemId: 'EPS-094',
  modifierGroups: []
},
{
  id: 'item-bahubali',
  categoryId: 'special-dosas',
  name: 'Bahubali Paper Roast',
  description: 'The Grand Dosa Feast that makes you fight like Bahubali.',
  price: 3999,
  image: 'https://dosacompany.co.uk/wp-content/uploads/2026/01/BahubaliPaperRoas.jpeg',
  alt: 'Enormous Bahubali paper roast dosa showstopper dish',
  isVegetarian: true,
  spiceLevel: 'mild',
  allergens: ['dairy'],
  available: true,
  featured: true,
  eposItemId: 'EPS-095',
  modifierGroups: []
},

// ─── BREADS & CURRIES ────────────────────────────────────────────────────────
{
  id: 'item-naan',
  categoryId: 'breads-curries',
  name: 'Naan',
  description: 'Plain refined flour flat bread cooked in clay oven.',
  price: 299,
  image: 'https://dosacompany.co.uk/wp-content/uploads/2026/01/Naan.jpeg',
  alt: 'Plain naan bread cooked in tandoor clay oven',
  isVegetarian: true,
  spiceLevel: 'none',
  allergens: ['gluten', 'dairy'],
  available: true,
  featured: false,
  eposItemId: 'EPS-100',
  modifierGroups: []
},
{
  id: 'item-butter-naan',
  categoryId: 'breads-curries',
  name: 'Butter Naan',
  description: 'Plain refined flour flat bread cooked in clay oven with butter.',
  price: 375,
  image: 'https://dosacompany.co.uk/wp-content/uploads/2026/01/Gobi65.jpeg',
  alt: 'Butter naan with golden butter on top',
  isVegetarian: true,
  spiceLevel: 'none',
  allergens: ['gluten', 'dairy'],
  available: true,
  featured: false,
  eposItemId: 'EPS-101',
  modifierGroups: []
},
{
  id: 'item-roti',
  categoryId: 'breads-curries',
  name: 'Roti',
  description: 'Whole wheat flat bread cooked in clay oven.',
  price: 299,
  image: 'https://dosacompany.co.uk/wp-content/uploads/2026/01/Roti.jpeg',
  alt: 'Whole wheat roti flatbread from tandoor oven',
  isVegetarian: true,
  spiceLevel: 'none',
  allergens: ['gluten'],
  available: true,
  featured: false,
  eposItemId: 'EPS-102',
  modifierGroups: []
},
{
  id: 'item-butter-roti',
  categoryId: 'breads-curries',
  name: 'Butter Roti',
  description: 'Whole wheat flat bread cooked in clay oven with butter.',
  price: 375,
  image: 'https://dosacompany.co.uk/wp-content/uploads/2026/01/Butterroti.jpeg',
  alt: 'Butter roti with melted butter on whole wheat flatbread',
  isVegetarian: true,
  spiceLevel: 'none',
  allergens: ['gluten', 'dairy'],
  available: true,
  featured: false,
  eposItemId: 'EPS-103',
  modifierGroups: []
},
{
  id: 'item-garlic-naan',
  categoryId: 'breads-curries',
  name: 'Garlic Naan',
  description: 'Garlic sprinkled on refined flour flat bread cooked in clay oven.',
  price: 349,
  image: 'https://dosacompany.co.uk/wp-content/uploads/2026/01/Garlicnaan.jpeg',
  alt: 'Garlic naan with roasted garlic and herbs',
  isVegetarian: true,
  spiceLevel: 'none',
  allergens: ['gluten', 'dairy'],
  available: true,
  featured: false,
  eposItemId: 'EPS-104',
  modifierGroups: []
},
{
  id: 'item-chilly-garlic-naan',
  categoryId: 'breads-curries',
  name: 'Chilly Garlic Naan',
  description: 'Garlic, green chillies sprinkled on refined flour flat bread cooked in clay oven.',
  price: 399,
  image: 'https://dosacompany.co.uk/wp-content/uploads/2026/01/ChilliGarlicNaan.jpeg',
  alt: 'Chilli garlic naan with green chillies and garlic topping',
  isVegetarian: true,
  spiceLevel: 'hot',
  allergens: ['gluten', 'dairy'],
  available: true,
  featured: false,
  eposItemId: 'EPS-105',
  modifierGroups: []
},
{
  id: 'item-mixed-veg-curry',
  categoryId: 'breads-curries',
  name: 'Mixed Vegetable Curry',
  description: 'Assorted vegetables cooked with onion & tomato.',
  price: 799,
  image: 'https://dosacompany.co.uk/wp-content/uploads/2026/01/Mixvegkurma.jpeg',
  alt: 'Mixed vegetable curry with colourful vegetables in tomato gravy',
  isVegetarian: true,
  spiceLevel: 'medium',
  allergens: [],
  available: true,
  featured: false,
  eposItemId: 'EPS-106',
  modifierGroups: []
},
{
  id: 'item-paneer-butter-masala',
  categoryId: 'breads-curries',
  name: 'Paneer Butter Masala',
  description: 'Homemade cottage cheese cooked with tomato.',
  price: 950,
  image: 'https://dosacompany.co.uk/wp-content/uploads/2026/01/Paneerbuttermasala.jpeg',
  alt: 'Paneer butter masala in rich tomato cream sauce',
  isVegetarian: true,
  spiceLevel: 'mild',
  allergens: ['dairy'],
  available: true,
  featured: true,
  eposItemId: 'EPS-107',
  modifierGroups: []
},
{
  id: 'item-channa-masala',
  categoryId: 'breads-curries',
  name: 'Channa Masala',
  description: 'Boiled chickpeas cooked with spiced onion and tomato masala.',
  price: 775,
  image: 'https://dosacompany.co.uk/wp-content/uploads/2026/01/Channamasala.jpeg',
  alt: 'Channa masala chickpea curry with spiced tomato gravy',
  isVegetarian: true,
  spiceLevel: 'medium',
  allergens: [],
  available: true,
  featured: false,
  eposItemId: 'EPS-108',
  modifierGroups: []
},
{
  id: 'item-palak-paneer',
  categoryId: 'breads-curries',
  name: 'Palak Paneer',
  description: 'Cubed cottage cheese cooked with spinach purée.',
  price: 950,
  image: 'https://dosacompany.co.uk/wp-content/uploads/2026/01/Palakpaneer.jpeg',
  alt: 'Palak paneer with green spinach sauce and white paneer cubes',
  isVegetarian: true,
  spiceLevel: 'mild',
  allergens: ['dairy'],
  available: true,
  featured: false,
  eposItemId: 'EPS-109',
  modifierGroups: []
},
{
  id: 'item-aloo-gobi-masala',
  categoryId: 'breads-curries',
  name: 'Aloo Gobi Masala',
  description: 'Potato and cauliflower cooked with spiced masala.',
  price: 850,
  image: 'https://dosacompany.co.uk/wp-content/uploads/2026/01/AlooGobiMasa.jpeg',
  alt: 'Aloo gobi masala with potatoes and cauliflower in spiced gravy',
  isVegetarian: true,
  spiceLevel: 'medium',
  allergens: [],
  available: true,
  featured: false,
  eposItemId: 'EPS-110',
  modifierGroups: []
},
{
  id: 'item-paneer-tikka-masala',
  categoryId: 'breads-curries',
  name: 'Paneer Tikka Masala',
  description: 'Clay oven roasted cottage cheese cooked in rich masala sauce.',
  price: 999,
  image: 'https://dosacompany.co.uk/wp-content/uploads/2026/01/Paneertikkamasala.jpeg',
  alt: 'Paneer tikka masala with charred paneer in rich orange sauce',
  isVegetarian: true,
  spiceLevel: 'medium',
  allergens: ['dairy'],
  available: true,
  featured: false,
  eposItemId: 'EPS-111',
  modifierGroups: []
},
{
  id: 'item-dhal-tadka',
  categoryId: 'breads-curries',
  name: 'Dhal Tadka',
  description: 'Boiled lentils tempered with Indian spices.',
  price: 799,
  image: 'https://dosacompany.co.uk/wp-content/uploads/2026/01/Daltadka.jpeg',
  alt: 'Dhal tadka yellow lentil curry with spiced tempering',
  isVegetarian: true,
  spiceLevel: 'mild',
  allergens: [],
  available: true,
  featured: false,
  eposItemId: 'EPS-112',
  modifierGroups: []
},
{
  id: 'item-dhal-makhani',
  categoryId: 'breads-curries',
  name: 'Dhal Makhani',
  description: 'Black urid dhal cooked with butter, cream, tomato.',
  price: 850,
  image: 'https://dosacompany.co.uk/wp-content/uploads/2026/01/Dalmakhani.jpeg',
  alt: 'Creamy dhal makhani black lentil curry with butter and cream',
  isVegetarian: true,
  spiceLevel: 'mild',
  allergens: ['dairy'],
  available: true,
  featured: false,
  eposItemId: 'EPS-113',
  modifierGroups: []
},
{
  id: 'item-mushroom-masala',
  categoryId: 'breads-curries',
  name: 'Mushroom Masala',
  description: 'Button mushrooms cooked in rich spiced masala gravy.',
  price: 999,
  image: 'https://dosacompany.co.uk/wp-content/uploads/2026/01/MushroomMasal.jpeg',
  alt: 'Mushroom masala with button mushrooms in spiced gravy',
  isVegetarian: true,
  spiceLevel: 'medium',
  allergens: [],
  available: true,
  featured: false,
  eposItemId: 'EPS-114',
  modifierGroups: []
},
{
  id: 'item-bhindi-kadai',
  categoryId: 'breads-curries',
  name: 'Bhindi Kadai',
  description: 'Okra cooked in kadai with spiced onion tomato masala.',
  price: 999,
  image: 'https://dosacompany.co.uk/wp-content/uploads/2026/01/BhindiKada.jpeg',
  alt: 'Bhindi kadai okra curry in a wok with spiced masala',
  isVegetarian: true,
  spiceLevel: 'medium',
  allergens: [],
  available: true,
  featured: false,
  eposItemId: 'EPS-115',
  modifierGroups: []
},
{
  id: 'item-mutter-paneer',
  categoryId: 'breads-curries',
  name: 'Mutter Paneer',
  description: 'Green peas and cottage cheese cooked in spiced gravy.',
  price: 999,
  image: 'https://dosacompany.co.uk/wp-content/uploads/2026/01/MutterPanee.jpeg',
  alt: 'Mutter paneer with green peas and paneer in tomato gravy',
  isVegetarian: true,
  spiceLevel: 'medium',
  allergens: ['dairy'],
  available: true,
  featured: false,
  eposItemId: 'EPS-116',
  modifierGroups: []
},
{
  id: 'item-sprouts-curry',
  categoryId: 'breads-curries',
  name: "Chef's Special Sprouts Curry",
  description: "Chef's special sprouts cooked in aromatic curry.",
  price: 999,
  image: 'https://dosacompany.co.uk/wp-content/uploads/2026/01/ChefsSpecialsproutscurr.jpeg',
  alt: "Chef's special sprouts curry with mixed sprouts in spiced gravy",
  isVegetarian: true,
  spiceLevel: 'medium',
  allergens: [],
  available: true,
  featured: false,
  eposItemId: 'EPS-117',
  modifierGroups: []
},
{
  id: 'item-paneer-momos',
  categoryId: 'breads-curries',
  name: 'Paneer Momos (Dumplings)',
  description: 'Steamed dumplings filled with spiced paneer.',
  price: 999,
  image: 'https://dosacompany.co.uk/wp-content/uploads/2026/01/PaneerMomosDumpling.jpeg',
  alt: 'Paneer momos steamed dumplings with dipping sauce',
  isVegetarian: true,
  spiceLevel: 'mild',
  allergens: ['dairy', 'gluten'],
  available: true,
  featured: false,
  eposItemId: 'EPS-118',
  modifierGroups: []
},

// ─── RICE & NOODLES ──────────────────────────────────────────────────────────
{
  id: 'item-madras-biryani',
  categoryId: 'rice-noodles',
  name: 'Madras Spl Biryani',
  description: 'Our flavourful biryani with Gobi 65 pieces.',
  price: 825,
  image: 'https://dosacompany.co.uk/wp-content/uploads/2026/01/MadrasSplBiryan.jpeg',
  alt: 'Madras special biryani with Gobi 65 and aromatic basmati rice',
  isVegetarian: true,
  spiceLevel: 'medium',
  allergens: ['gluten'],
  available: true,
  featured: false,
  eposItemId: 'EPS-120',
  modifierGroups: []
},
{
  id: 'item-veg-biryani',
  categoryId: 'rice-noodles',
  name: 'Vegetable Biryani',
  description: 'Basmati rice cooked with mixed vegetables & Indian spices.',
  price: 799,
  image: 'https://dosacompany.co.uk/wp-content/uploads/2026/01/VegetableBiryan.jpeg',
  alt: 'Vegetable biryani with colourful vegetables and basmati rice',
  isVegetarian: true,
  spiceLevel: 'medium',
  allergens: [],
  available: true,
  featured: false,
  eposItemId: 'EPS-121',
  modifierGroups: []
},
{
  id: 'item-veg-fried-rice',
  categoryId: 'rice-noodles',
  name: 'Vegetable Fried Rice',
  description: 'Fried rice with various types of vegetables.',
  price: 850,
  image: 'https://dosacompany.co.uk/wp-content/uploads/2026/01/VegFriedRice-1.jpeg',
  alt: 'Vegetable fried rice with mixed vegetables and soy sauce',
  isVegetarian: true,
  spiceLevel: 'mild',
  allergens: ['soy'],
  available: true,
  featured: false,
  eposItemId: 'EPS-122',
  modifierGroups: []
},
{
  id: 'item-schezwan-fried-rice',
  categoryId: 'rice-noodles',
  name: 'Schezwan Fried Rice',
  description: 'Spicy Schezwan style fried rice.',
  price: 850,
  image: 'https://dosacompany.co.uk/wp-content/uploads/2026/01/SchezwanFriedRice.jpeg',
  alt: 'Schezwan fried rice with spicy red sauce and vegetables',
  isVegetarian: true,
  spiceLevel: 'hot',
  allergens: ['soy'],
  available: true,
  featured: false,
  eposItemId: 'EPS-123',
  modifierGroups: []
},
{
  id: 'item-jeera-rice',
  categoryId: 'rice-noodles',
  name: 'Jeera Rice',
  description: 'Fluffy basmati rice tossed with tempered cumin seeds & mild spices.',
  price: 750,
  image: 'https://dosacompany.co.uk/wp-content/uploads/2026/01/JeeraRic.jpeg',
  alt: 'Jeera rice with cumin seeds and basmati rice',
  isVegetarian: true,
  spiceLevel: 'none',
  allergens: [],
  available: true,
  featured: false,
  eposItemId: 'EPS-124',
  modifierGroups: []
},
{
  id: 'item-veg-noodles',
  categoryId: 'rice-noodles',
  name: 'Vegetable Noodles',
  description: 'Stir-fried noodles with assorted vegetables.',
  price: 850,
  image: 'https://dosacompany.co.uk/wp-content/uploads/2026/01/Vegnoodles.jpeg',
  alt: 'Vegetable noodles stir-fried with colourful vegetables',
  isVegetarian: true,
  spiceLevel: 'mild',
  allergens: ['gluten', 'soy'],
  available: true,
  featured: false,
  eposItemId: 'EPS-125',
  modifierGroups: []
},
{
  id: 'item-schezwan-noodles',
  categoryId: 'rice-noodles',
  name: 'Schezwan Noodles',
  description: 'Assorted vegetables cooked with Schezwan sauce and noodles.',
  price: 850,
  image: 'https://dosacompany.co.uk/wp-content/uploads/2026/01/schezwannoodles.jpeg',
  alt: 'Schezwan noodles with spicy sauce and vegetables',
  isVegetarian: true,
  spiceLevel: 'hot',
  allergens: ['gluten', 'soy'],
  available: true,
  featured: false,
  eposItemId: 'EPS-126',
  modifierGroups: []
},
{
  id: 'item-fried-rice-special',
  categoryId: 'rice-noodles',
  name: 'Fried Rice (Mushroom/Gobi/Paneer)',
  description: 'Choice of mushroom, gobi or paneer fried rice.',
  price: 949,
  image: 'https://dosacompany.co.uk/wp-content/uploads/2026/01/FriedRic.jpeg',
  alt: 'Special fried rice with mushroom, gobi or paneer',
  isVegetarian: true,
  spiceLevel: 'mild',
  allergens: ['soy'],
  available: true,
  featured: false,
  eposItemId: 'EPS-127',
  modifierGroups: [
  {
    id: 'mg-fried-rice-type',
    label: 'Choose Type',
    required: true,
    multiSelect: false,
    options: [
    { id: 'opt-mushroom', label: 'Mushroom', extraPrice: 0 },
    { id: 'opt-gobi', label: 'Gobi', extraPrice: 0 },
    { id: 'opt-paneer', label: 'Paneer', extraPrice: 0 }]

  }]

},

// ─── CHAAT & SPECIALS ────────────────────────────────────────────────────────
{
  id: 'item-panipuri',
  categoryId: 'chaat',
  name: 'Panipuri',
  description: 'Crispy hollow puris filled with spiced water and chutney.',
  price: 649,
  image: 'https://dosacompany.co.uk/wp-content/uploads/2026/01/Panipur.jpeg',
  alt: 'Panipuri crispy hollow puris with spiced tamarind water',
  isVegetarian: true,
  spiceLevel: 'medium',
  allergens: ['gluten'],
  available: true,
  featured: false,
  eposItemId: 'EPS-130',
  modifierGroups: []
},
{
  id: 'item-aloo-papdi-chaat',
  categoryId: 'chaat',
  name: 'Aloo Papdi Chaat',
  description: 'Crispy papdi with potatoes, chutneys and yoghurt.',
  price: 649,
  image: 'https://dosacompany.co.uk/wp-content/uploads/2026/01/AlooPapdiChaa.jpeg',
  alt: 'Aloo papdi chaat with crispy papdi, potatoes and chutneys',
  isVegetarian: true,
  spiceLevel: 'medium',
  allergens: ['gluten', 'dairy'],
  available: true,
  featured: false,
  eposItemId: 'EPS-131',
  modifierGroups: []
},
{
  id: 'item-bhel-puri',
  categoryId: 'chaat',
  name: 'Bhel Puri',
  description: 'Puffed rice mixed with vegetables, chutneys and sev.',
  price: 649,
  image: 'https://dosacompany.co.uk/wp-content/uploads/2026/01/BhelPur.jpeg',
  alt: 'Bhel puri with puffed rice, vegetables and tamarind chutney',
  isVegetarian: true,
  spiceLevel: 'mild',
  allergens: ['gluten'],
  available: true,
  featured: false,
  eposItemId: 'EPS-132',
  modifierGroups: []
},
{
  id: 'item-dahi-puri',
  categoryId: 'chaat',
  name: 'Dahi Puri',
  description: 'Crispy puris filled with yoghurt, chutneys and spices.',
  price: 649,
  image: 'https://dosacompany.co.uk/wp-content/uploads/2026/01/DahiPur.jpeg',
  alt: 'Dahi puri with yoghurt, tamarind chutney and sev',
  isVegetarian: true,
  spiceLevel: 'mild',
  allergens: ['gluten', 'dairy'],
  available: true,
  featured: false,
  eposItemId: 'EPS-133',
  modifierGroups: []
},
{
  id: 'item-sev-puri',
  categoryId: 'chaat',
  name: 'Sev Puri',
  description: 'Crispy puris topped with sev, chutneys and spices.',
  price: 649,
  image: 'https://dosacompany.co.uk/wp-content/uploads/2026/01/SevPur.jpeg',
  alt: 'Sev puri with crispy sev, chutneys and spiced toppings',
  isVegetarian: true,
  spiceLevel: 'mild',
  allergens: ['gluten'],
  available: true,
  featured: false,
  eposItemId: 'EPS-134',
  modifierGroups: []
},

// ─── DESSERTS ────────────────────────────────────────────────────────────────
{
  id: 'item-ice-cream',
  categoryId: 'desserts',
  name: 'Choice of Ice Cream',
  description: 'Your choice of flavours.',
  price: 350,
  image: 'https://dosacompany.co.uk/wp-content/uploads/2026/01/ChoiceofIceCrea.jpeg',
  alt: 'Scoops of ice cream in various flavours',
  isVegetarian: true,
  spiceLevel: 'none',
  allergens: ['dairy'],
  available: true,
  featured: false,
  eposItemId: 'EPS-140',
  modifierGroups: []
},
{
  id: 'item-gulab-jamun',
  categoryId: 'desserts',
  name: 'Gulab Jamun (2 Pcs)',
  description: 'Milk-based sweet balls served with sugar syrup & nuts.',
  price: 399,
  image: 'https://dosacompany.co.uk/wp-content/uploads/2026/01/GulabJamu.jpeg',
  alt: 'Two gulab jamun sweet balls in sugar syrup with nuts',
  isVegetarian: true,
  spiceLevel: 'none',
  allergens: ['dairy', 'gluten', 'nuts'],
  available: true,
  featured: false,
  eposItemId: 'EPS-141',
  modifierGroups: []
},
{
  id: 'item-carrot-halwa',
  categoryId: 'desserts',
  name: 'Carrot Halwa',
  description: 'Pudding of carrot, sugar and ghee.',
  price: 399,
  image: 'https://dosacompany.co.uk/wp-content/uploads/2026/01/CarrotHalw.jpeg',
  alt: 'Carrot halwa gajar ka halwa with ghee and nuts',
  isVegetarian: true,
  spiceLevel: 'none',
  allergens: ['dairy', 'nuts'],
  available: true,
  featured: false,
  eposItemId: 'EPS-142',
  modifierGroups: []
},
{
  id: 'item-badam-halwa',
  categoryId: 'desserts',
  name: 'Badam Halwa',
  description: 'Pudding of almond, saffron, sugar and ghee.',
  price: 475,
  image: 'https://dosacompany.co.uk/wp-content/uploads/2026/01/BadamHalw.jpeg',
  alt: 'Badam halwa almond pudding with saffron and ghee',
  isVegetarian: true,
  spiceLevel: 'none',
  allergens: ['dairy', 'nuts'],
  available: true,
  featured: false,
  eposItemId: 'EPS-143',
  modifierGroups: []
},
{
  id: 'item-rasamalai',
  categoryId: 'desserts',
  name: 'Rasamalai (2 Pcs)',
  description: 'Soft paneer patties in sweetened saffron milk.',
  price: 425,
  image: 'https://dosacompany.co.uk/wp-content/uploads/2026/01/Rasamalai2Pc.jpeg',
  alt: 'Rasamalai soft cheese patties in saffron milk',
  isVegetarian: true,
  spiceLevel: 'none',
  allergens: ['dairy'],
  available: true,
  featured: false,
  eposItemId: 'EPS-144',
  modifierGroups: []
},
{
  id: 'item-sweet-of-day',
  categoryId: 'desserts',
  name: 'Sweet of the Day',
  description: 'Ask our waiter for the speciality of the day.',
  price: 399,
  image: 'https://dosacompany.co.uk/wp-content/uploads/2026/01/SweetoftheDa.jpeg',
  alt: 'Sweet of the day special dessert',
  isVegetarian: true,
  spiceLevel: 'none',
  allergens: ['dairy'],
  available: true,
  featured: false,
  eposItemId: 'EPS-145',
  modifierGroups: []
},
{
  id: 'item-stick-kulfi',
  categoryId: 'desserts',
  name: 'Stick Kulfi',
  description: 'Pista, mango or malgai flavoured kulfi on a stick.',
  price: 325,
  image: 'https://dosacompany.co.uk/wp-content/uploads/2026/01/StickKulf.jpeg',
  alt: 'Stick kulfi Indian ice cream on a stick',
  isVegetarian: true,
  spiceLevel: 'none',
  allergens: ['dairy', 'nuts'],
  available: true,
  featured: false,
  eposItemId: 'EPS-146',
  modifierGroups: [
  {
    id: 'mg-kulfi-flavour',
    label: 'Choose Flavour',
    required: true,
    multiSelect: false,
    options: [
    { id: 'opt-pista', label: 'Pista', extraPrice: 0 },
    { id: 'opt-mango', label: 'Mango', extraPrice: 0 },
    { id: 'opt-malgai', label: 'Malgai', extraPrice: 0 }]

  }]

},
{
  id: 'item-matka-kulfi',
  categoryId: 'desserts',
  name: 'Matka Kulfi',
  description: 'Traditional kulfi served in a clay pot.',
  price: 499,
  image: 'https://dosacompany.co.uk/wp-content/uploads/2026/01/MatkaKulf.jpeg',
  alt: 'Matka kulfi Indian ice cream served in a clay pot',
  isVegetarian: true,
  spiceLevel: 'none',
  allergens: ['dairy', 'nuts'],
  available: true,
  featured: false,
  eposItemId: 'EPS-147',
  modifierGroups: []
},
{
  id: 'item-honeycomb-ice-cream',
  categoryId: 'desserts',
  name: 'Honeycomb Ice Cream',
  description: 'Rich honeycomb flavoured ice cream.',
  price: 650,
  image: 'https://dosacompany.co.uk/wp-content/uploads/2026/01/HoneycombIceCrea.jpeg',
  alt: 'Honeycomb ice cream with golden honeycomb pieces',
  isVegetarian: true,
  spiceLevel: 'none',
  allergens: ['dairy'],
  available: true,
  featured: false,
  eposItemId: 'EPS-148',
  modifierGroups: []
},
{
  id: 'item-toy-ice-cream',
  categoryId: 'desserts',
  name: 'Toy Ice Cream',
  description: 'Fun toy ice cream for kids and adults.',
  price: 450,
  image: 'https://dosacompany.co.uk/wp-content/uploads/2026/01/ToyIceCrea.jpeg',
  alt: 'Toy ice cream fun shaped dessert',
  isVegetarian: true,
  spiceLevel: 'none',
  allergens: ['dairy'],
  available: true,
  featured: false,
  eposItemId: 'EPS-149',
  modifierGroups: []
},

// ─── DRINKS ──────────────────────────────────────────────────────────────────
{
  id: 'item-fresh-fruit-juice',
  categoryId: 'drinks',
  name: 'Fresh Fruit Juices',
  description: 'Orange, pomegranate, pineapple or seasonal fruits.',
  price: 550,
  image: 'https://dosacompany.co.uk/wp-content/uploads/2026/01/FreshFruitJuice.jpeg',
  alt: 'Fresh fruit juice in a glass with fruit slices',
  isVegetarian: true,
  spiceLevel: 'none',
  allergens: [],
  available: true,
  featured: false,
  eposItemId: 'EPS-150',
  modifierGroups: [
  {
    id: 'mg-juice-flavour',
    label: 'Choose Flavour',
    required: true,
    multiSelect: false,
    options: [
    { id: 'opt-orange', label: 'Orange', extraPrice: 0 },
    { id: 'opt-pomegranate', label: 'Pomegranate', extraPrice: 0 },
    { id: 'opt-pineapple', label: 'Pineapple', extraPrice: 0 },
    { id: 'opt-seasonal', label: 'Seasonal', extraPrice: 0 }]

  }]

},
{
  id: 'item-milk-shake',
  categoryId: 'drinks',
  name: 'Milk Shakes',
  description: 'Creamy, chilled, sweet blended delight.',
  price: 499,
  image: 'https://dosacompany.co.uk/wp-content/uploads/2026/01/MilkShake.jpeg',
  alt: 'Creamy milkshake in a tall glass with whipped cream',
  isVegetarian: true,
  spiceLevel: 'none',
  allergens: ['dairy'],
  available: true,
  featured: false,
  eposItemId: 'EPS-151',
  modifierGroups: []
},
{
  id: 'item-soft-drinks',
  categoryId: 'drinks',
  name: 'Coke/Diet Coke/Fanta/Sprite',
  description: 'Classic, fizzy, refreshing soft drinks.',
  price: 350,
  image: 'https://dosacompany.co.uk/wp-content/uploads/2026/01/Coke.jpeg',
  alt: 'Coke soft drink can with ice',
  isVegetarian: true,
  spiceLevel: 'none',
  allergens: [],
  available: true,
  featured: false,
  eposItemId: 'EPS-152',
  modifierGroups: [
  {
    id: 'mg-soft-drink-type',
    label: 'Choose Drink',
    required: true,
    multiSelect: false,
    options: [
    { id: 'opt-coke', label: 'Coke', extraPrice: 0 },
    { id: 'opt-diet-coke', label: 'Diet Coke', extraPrice: 0 },
    { id: 'opt-fanta', label: 'Fanta', extraPrice: 0 },
    { id: 'opt-sprite', label: 'Sprite', extraPrice: 0 }]

  }]

},
{
  id: 'item-lassi',
  categoryId: 'drinks',
  name: 'Lassi (Sweet/Salt/Mango)',
  description: 'Refreshing, traditional, yogurt-based drink.',
  price: 499,
  image: 'https://dosacompany.co.uk/wp-content/uploads/2026/01/LassiSweetSaltMang.jpeg',
  alt: 'Lassi yoghurt drink in a glass with rose petals',
  isVegetarian: true,
  spiceLevel: 'none',
  allergens: ['dairy'],
  available: true,
  featured: false,
  eposItemId: 'EPS-153',
  modifierGroups: [
  {
    id: 'mg-lassi-type',
    label: 'Choose Type',
    required: true,
    multiSelect: false,
    options: [
    { id: 'opt-sweet', label: 'Sweet', extraPrice: 0 },
    { id: 'opt-salt', label: 'Salt', extraPrice: 0 },
    { id: 'opt-mango', label: 'Mango', extraPrice: 0 }]

  }]

},
{
  id: 'item-special-baang-lassi',
  categoryId: 'drinks',
  name: 'Special Baang Lassi',
  description: 'Unique, rich, flavourful yogurt blend.',
  price: 650,
  image: 'https://dosacompany.co.uk/wp-content/uploads/2026/01/SpecialBaangLass.jpeg',
  alt: 'Special baang lassi in a decorated glass',
  isVegetarian: true,
  spiceLevel: 'none',
  allergens: ['dairy'],
  available: true,
  featured: false,
  eposItemId: 'EPS-154',
  modifierGroups: []
},
{
  id: 'item-butter-milk',
  categoryId: 'drinks',
  name: 'Butter Milk',
  description: 'Cool, spiced, light digestive drink.',
  price: 450,
  image: 'https://dosacompany.co.uk/wp-content/uploads/2026/01/ButterMil.jpeg',
  alt: 'Spiced buttermilk in a glass with curry leaves',
  isVegetarian: true,
  spiceLevel: 'none',
  allergens: ['dairy'],
  available: true,
  featured: false,
  eposItemId: 'EPS-155',
  modifierGroups: []
},
{
  id: 'item-rose-milk',
  categoryId: 'drinks',
  name: 'Rose Milk',
  description: 'Fragrant, pink, sweet floral refreshment.',
  price: 499,
  image: 'https://dosacompany.co.uk/wp-content/uploads/2026/01/RoseMil.jpeg',
  alt: 'Pink rose milk in a glass with rose petals',
  isVegetarian: true,
  spiceLevel: 'none',
  allergens: ['dairy'],
  available: true,
  featured: false,
  eposItemId: 'EPS-156',
  modifierGroups: []
},
{
  id: 'item-filter-coffee',
  categoryId: 'drinks',
  name: 'Filter Coffee / Masala Tea',
  description: 'Authentic South Indian filter coffee or spiced masala tea.',
  price: 250,
  image: 'https://dosacompany.co.uk/wp-content/uploads/2026/01/FilterCoffeeMasala.jpeg',
  alt: 'South Indian filter coffee in a traditional tumbler and davara',
  isVegetarian: true,
  spiceLevel: 'none',
  allergens: ['dairy'],
  available: true,
  featured: false,
  eposItemId: 'EPS-157',
  modifierGroups: [
  {
    id: 'mg-coffee-tea',
    label: 'Choose',
    required: true,
    multiSelect: false,
    options: [
    { id: 'opt-filter-coffee', label: 'Filter Coffee', extraPrice: 0 },
    { id: 'opt-masala-tea', label: 'Masala Tea', extraPrice: 0 }]

  }]

},
{
  id: 'item-paan-milkshake',
  categoryId: 'drinks',
  name: 'Paan Milkshake',
  description: 'A refreshing blend of paan flavour and creamy milk.',
  price: 650,
  image: 'https://dosacompany.co.uk/wp-content/uploads/2026/01/PaanMilkshak.jpeg',
  alt: 'Paan milkshake in a green glass with paan leaves',
  isVegetarian: true,
  spiceLevel: 'none',
  allergens: ['dairy'],
  available: true,
  featured: false,
  eposItemId: 'EPS-158',
  modifierGroups: []
},
{
  id: 'item-oreo-milkshake',
  categoryId: 'drinks',
  name: 'Oreo Milkshake',
  description: 'Classic Oreo biscuits blended into a rich, creamy milkshake.',
  price: 650,
  image: 'https://dosacompany.co.uk/wp-content/uploads/2026/01/OreoMilkshak.jpeg',
  alt: 'Oreo milkshake with crushed Oreo biscuits and cream',
  isVegetarian: true,
  spiceLevel: 'none',
  allergens: ['dairy', 'gluten'],
  available: true,
  featured: false,
  eposItemId: 'EPS-159',
  modifierGroups: []
},
{
  id: 'item-dryfruit-milkshake',
  categoryId: 'drinks',
  name: 'Dry Fruit Milkshake',
  description: 'Nutritious and flavourful shake with rich dry fruits and milk.',
  price: 650,
  image: 'https://dosacompany.co.uk/wp-content/uploads/2026/01/DryFruitMilkshak.jpeg',
  alt: 'Dry fruit milkshake with almonds, cashews and pistachios',
  isVegetarian: true,
  spiceLevel: 'none',
  allergens: ['dairy', 'nuts'],
  available: true,
  featured: false,
  eposItemId: 'EPS-160',
  modifierGroups: []
},
{
  id: 'item-kitkat-milkshake',
  categoryId: 'drinks',
  name: 'Kitkat Milkshake',
  description: 'KitKat chocolate blended into a creamy milkshake.',
  price: 650,
  image: 'https://dosacompany.co.uk/wp-content/uploads/2026/01/KitkatMilkshak.jpeg',
  alt: 'KitKat milkshake with chocolate wafer pieces',
  isVegetarian: true,
  spiceLevel: 'none',
  allergens: ['dairy', 'gluten'],
  available: true,
  featured: false,
  eposItemId: 'EPS-161',
  modifierGroups: []
},
{
  id: 'item-maltesers-milkshake',
  categoryId: 'drinks',
  name: 'Maltesers Milkshake',
  description: 'Maltesers blended into a rich, creamy milkshake.',
  price: 650,
  image: 'https://dosacompany.co.uk/wp-content/uploads/2026/01/MaltesersMilkshak.jpeg',
  alt: 'Maltesers milkshake with chocolate malt balls',
  isVegetarian: true,
  spiceLevel: 'none',
  allergens: ['dairy', 'gluten'],
  available: true,
  featured: false,
  eposItemId: 'EPS-162',
  modifierGroups: []
},
{
  id: 'item-ferrero-milkshake',
  categoryId: 'drinks',
  name: 'Ferrero Rocher Milkshake',
  description: 'Ferrero Rocher blended into a luxurious milkshake.',
  price: 650,
  image: 'https://dosacompany.co.uk/wp-content/uploads/2026/01/FerreroRocherMilkshak.jpeg',
  alt: 'Ferrero Rocher milkshake with hazelnut chocolate',
  isVegetarian: true,
  spiceLevel: 'none',
  allergens: ['dairy', 'nuts', 'gluten'],
  available: true,
  featured: false,
  eposItemId: 'EPS-163',
  modifierGroups: []
},
{
  id: 'item-kinder-milkshake',
  categoryId: 'drinks',
  name: 'Kinder Milkshake',
  description: 'Kinder chocolate blended into a creamy milkshake.',
  price: 650,
  image: 'https://dosacompany.co.uk/wp-content/uploads/2026/01/KinderMilkshak.jpeg',
  alt: 'Kinder milkshake with Kinder chocolate pieces',
  isVegetarian: true,
  spiceLevel: 'none',
  allergens: ['dairy', 'gluten'],
  available: true,
  featured: false,
  eposItemId: 'EPS-164',
  modifierGroups: []
}];


export function formatPrice(pence: number): string {
  return `£${(pence / 100).toFixed(2)}`;
}